Building
--------

Maven is used as build tool for jrobotremoteserver.
You can simply do a 'mvn clean install' in the project directory.

Robot Tests
-----------

There are some number of robot acceptance tests under `jrobot-kataf/src`.
