name: Java CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # test against LTS java versions:
        java: [ 11 ]
    name: Test with Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B verify --file pom.xml
  release:
    needs: [build_and_test]
    if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    name: Release package
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '8'
        cache: 'maven'
    - name: Release Maven package
      uses: samuelmeuli/action-maven-publish@201a45a3f311b2ee888f252ba9f4194257545709 # tag=v1.4.0
      with:
        gpg_private_key: ${{ secrets.gpg_private_key }}
        gpg_passphrase: ${{ secrets.gpg_passphrase }}
        nexus_username: ${{ secrets.nexus_username }}
        nexus_password: ${{ secrets.nexus_password }}
        maven_args: -DskipTests
